### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by KevinSupertramp** [KevinSupertramp/WakBox#3]
Just to remember, could be fun to make a JSON/WebAPI : http://www.makina-corpus.org/blog/access-json-webservice-qt-c

**Comment by totomakers** [comment]
Love it !

**Comment by KevinSupertramp** [comment]
:smile: 
Mais faut réussir à fixer ce problème de requêtes SOAP avant ! :tada:

**Comment by yggchan** [comment]
Can you describe the purpose of such thing, how it is related to wakfu ?

**Comment by KevinSupertramp** [comment]
No relation to Wakfu. It's related to the emulator and general data access :wink:

**Comment by KevinSupertramp** [comment]
Vu qu'on va devoir répondre à certaines requêtes SOAP pour le client, est-ce qu'on intègre ces "2 API" en un système (ce qui paraît le plus logique) ?

**Comment by totomakers** [comment]
Je suis pour que l'application Wakbox ne gère que la connection Wakfu -> Wakbox et que le stockage (avec api and co) soit géré par autre chose (style WakAPI)

<img src="http://image.noelshack.com/fichiers/2015/12/1426754877-diagramme1.png"/>

**Comment by Tamboz** [comment]
Hey can you make a hack for wakfu?

**Comment by Tamboz** [comment]
Sounds good, please look into it and let me know what you can do. Thanks

**Comment by KevinSupertramp** [comment]
I don't have any free time to look into it :/

**Comment by Tamboz** [comment]
But coukd you do it? If I hired you?

**Comment by KevinSupertramp** [comment]
Hi Tambosz, I can't be 100% sure as it would depends what kind of hack you are looking for. You can get in touch with me on the Wakbox Discord: https://discord.gg/qzVBDG

**Comment by Tamboz** [comment]
Ok great I joined the discord. My name is Bucky#9026. Whats yours?
